export const DEFAULT_SKIP_TAGS: readonly string[] = [
    "a",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "code",
    "pre",
    "kbd",
    "samp",
    "script",
    "style",
    "textarea",
    "ruby",
    "rt",
    "rp",
    "math",
    "svg",
] as const;